# Generated by Django 4.0.5 on 2022-06-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_is_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital_product',
            field=models.FileField(upload_to='digital-product/'),
        ),
    ]
