# Generated by Django 4.0.5 on 2022-06-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_digital_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital_product',
            field=models.FileField(blank=True, upload_to='digital-product/'),
        ),
    ]
